name: Build Kivy APK

on:
  push:
    branches:
      - main  # Cambia esto si quieres otro evento o rama específica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Versión compatible con Kivy

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Si tienes un archivo de dependencias
          pip install buildozer

      - name: Build APK with Buildozer
        run: buildozer -v android debug  # Cambia a release si quieres un build de producción

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: bin/*.apk  # Cambia esto si la ruta de tu APK es diferente
